#!/bin/bash
MAJOR=${1:-"1"}
MINOR=${2:-"32"}
BUGFIX=${3:-"0"}
echo "Building makerspace/makerspace-mediawiki:${MAJOR}.${MINOR}.${BUGFIX}"
docker build --tag=makerspace/makerspace-mediawiki:${MAJOR}.${MINOR}.${BUGFIX} \
    --build-arg MEDIAWIKI_VERSION_MAJOR=${MAJOR} \
    --build-arg MEDIAWIKI_VERSION_MINOR=${MINOR} \
    --build-arg MEDIAWIKI_VERSION_BUGFIX=${BUGFIX} \
    .
