# To use this image with docker-compose please look at the examples in example/docker-compose.
# This file is used for development together with .env which you can create by copying .env.default.
version: '3'
services:
  wiki:
    container_name: wiki.makerspace.se
    build:
      context: ./docker
      args:
        MEDIAWIKI_VERSION_MAJOR: 1
        MEDIAWIKI_VERSION_MINOR: 40
        MEDIAWIKI_VERSION_BUGFIX: 0
    links:
      - database
    restart: always
    environment:
      MEDIAWIKI_HTTPS: ${USE_HTTPS}
      MEDIAWIKI_SERVER: ${WIKI_HOST}
      MEDIAWIKI_SITENAME: Stockholm Makerspace Wiki
      MEDIAWIKI_LANGUAGE_CODE: sv
      MEDIAWIKI_SECRET_KEY: ${SECRET_KEY}
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: ${DB_HOST}
      MEDIAWIKI_DB_PORT: 3306
      MEDIAWIKI_DB_NAME: ${DB_NAME}
      MEDIAWIKI_DB_USER: ${DB_USER}
      MEDIAWIKI_DB_PREFIX: wiki_
      MEDIAWIKI_DB_TABLE_OPTIONS: ENGINE=InnoDB, DEFAULT CHARSET=binary
      MEDIAWIKI_DB_PASSWORD: ${DB_PASSWORD}
      MEDIAWIKI_ENABLE_UPLOADS: 1
      MEDIAWIKI_MAX_UPLOAD_SIZE: 10M
      MEDIAWIKI_DEFAULT_SKIN: vector
      MEDIAWIKI_SMTP: 1
      MEDIAWIKI_SMTP_SSL_VERIFY_PEER: 0
      MEDIAWIKI_SMTP_HOST: ${SMTP_HOST}
      MEDIAWIKI_SMTP_IDHOST: ${SMTP_IDHOST}
      MEDIAWIKI_SMTP_PORT: 587
      MEDIAWIKI_SMTP_AUTH: 1
      MEDIAWIKI_SMTP_USERNAME: ${SMTP_USERNAME}
      MEDIAWIKI_SMTP_PASSWORD: ${SMTP_PASSWORD}
      MEDIAWIKI_EMERGENCY_CONTACT: ${EMERGENCY_CONTACT}
      MEDIAWIKI_PASSWORD_SENDER: ${PASSWORD_SENDER}
      MEDIAWIKI_EXTENSION_VISUAL_EDITOR_ENABLED: 1
      MEDIAWIKI_EXTENSION_USER_MERGE_ENABLED: 1
      MEDIAWIKI_FILE_EXTENSIONS: png,gif,jpg,jpeg,webp,pdf
      MEDIAWIKI_DEBUG: 1
      PHPFPM_WORKERS_START: 1
      PHPFPM_WORKERS_MIN: 1
      PHPFPM_WORKERS_MAX: 20
      PARSOID_WORKERS: 1
      VIRTUAL_HOST:   wiki.makerspace.se
      LETSENCRYPT_HOST: wiki.makerspace.se
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NETWORKAUTH_IPRANGE: ${NETWORKAUTH_IPRANGE}
      NETWORKAUTH_USER: ${NETWORKAUTH_USER}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}

    volumes:
      - ./data/images:/var/www/html/images
      - ./data/makerspace_logo.png:/var/www/html/resources/assets/wiki.png:ro
      - ./data/makerspace_logo.svg:/var/www/html/resources/assets/wiki.svg:ro
      - ./data/ExtraLocalSettings.php:/var/www/html/ExtraLocalSettings.php:ro
      - ./data/LocalSettings.php:/var/www/html/LocalSettings.php:ro
      - ./data/php.ini:/usr/local/etc/php/conf.d/makerspace.ini

    expose:
      - "80"
    networks:
      - makerspace_wiki
      - internal
  database:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
      - ./data/mariadb.conf:/etc/mysql/mariadb.cnf
    networks:
      - internal
volumes:
  db:
networks:
  makerspace_wiki:
  internal:

# uncomment these if run without proxy
#    ports:
#      - "80:80"
